apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim1
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc1
  resources:
    requests:
      storage: 5Gi